blank_issues_enabled: false
contact_links:
  - name: 💬 Questions or Discussion
    url: https://github.com/Pepen0/Slipstreamdiscussions
    about: Please use Discussions for general help, Q&A, or ideas not yet ready for an issue.
